# Generated by Django 5.0.1 on 2024-01-29 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelter_app', '0002_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='shelteragents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agentname', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('psold', models.IntegerField()),
                ('agentimage', models.ImageField(upload_to='image')),
            ],
        ),
        migrations.AlterField(
            model_name='contact',
            name='mob1',
            field=models.BigIntegerField(verbose_name='Mobile 1'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='mob2',
            field=models.BigIntegerField(verbose_name='Mobile 2'),
        ),
    ]
