# Generated by Django 5.0.1 on 2024-01-29 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelter_app', '0003_shelteragents_alter_contact_mob1_alter_contact_mob2'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelteragents',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Available'),
        ),
    ]
