# Generated by Django 5.0.1 on 2024-01-29 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shelter_app', '0005_properties'),
    ]

    operations = [
        migrations.DeleteModel(
            name='properties',
        ),
    ]
