# Generated by Django 5.0.1 on 2024-01-29 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelter_app', '0012_alter_shelterproperties_pimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelterproperties',
            name='pimage',
            field=models.ImageField(upload_to='propertyimg'),
        ),
    ]
