# Generated by Django 5.0.1 on 2024-01-30 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelter_app', '0015_shelterproperties_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelterproperties',
            name='ptype1',
            field=models.CharField(choices=[(1, 'Land'), (2, 'Residential'), (3, 'Commercial'), (4, 'Industrial')], max_length=50),
        ),
    ]
