# Generated by Django 5.0.1 on 2024-01-30 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelter_app', '0016_alter_shelterproperties_ptype1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelterproperties',
            name='ptype1',
            field=models.IntegerField(choices=[(1, 'Land'), (2, 'Residential'), (3, 'Commercial'), (4, 'Industrial')]),
        ),
    ]
