# Generated by Django 5.0.1 on 2024-01-30 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelter_app', '0017_alter_shelterproperties_ptype1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelterproperties',
            name='ptype2',
            field=models.IntegerField(choices=[(1, 'Sale'), (2, 'Rent')]),
        ),
    ]
